pages:
  stage: deploy
  script:
    - mkdir public
    - cp -vr index.html public/index.html
    - cp -vr Praesentationskurs/out/praesentationskurs.pdf public/praesentationskurs.pdf
    - cp -vr Hauptvortrag/dist/. public/hauptvortrag
    - cp -vr Hack/dist/. public/hack
  artifacts:
    paths:
      - public
  only:
    - main
